name: DeaDBeeF Plugin Builder

on: [ push, pull_request, workflow_dispatch ]

env:
  ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION: node16
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build_linux:
    name: CI for Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout for Linux
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build and Upload for Linux
      uses: docker://ubuntu:20.04
      with:
        args: |
          /bin/bash -c "
            apt-get -qq update &&
            DEBIAN_FRONTEND=noninteractive apt-get install -y -qq autopoint automake autoconf intltool libc6-dev yasm libglib2.0-bin perl wget zip bzip2 make libtool pkg-config fakeroot clang openssh-client rsync git gcc g++ fontconfig xorg libharfbuzz0b libthai0 libwrap0 libsndfile1 libasyncns0 libjson-c-dev libglib2.0-dev-bin &&
            TRAVIS_OS_NAME=linux gh_ed25519_key= gh_ed25519_iv= travis/build.sh &&
            TRAVIS_OS_NAME=linux travis/upload.sh
          "
      env:
          gh_ed25519_key: ${{ secrets.GH_ENCRYPTED_ED25519_KEY }}
          gh_ed25519_iv: ${{ secrets.GH_ENCRYPTED_ED25519_IV }}
    - name: Upload linux plugin descriptors
      uses: actions/upload-artifact@v4
      with:
        name: plug-descr-linux
        path: temp/output/x86_64/*.descr
  build_macos:
    name: CI for macOS
    runs-on: macos-latest

    steps:
    - name: Checkout for macOS
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build for macOS
      run: TRAVIS_OS_NAME=osx travis/build.sh
    - name: Upload for macOS
      env:
          gh_ed25519_key: ${{ secrets.GH_ENCRYPTED_ED25519_KEY }}
          gh_ed25519_iv: ${{ secrets.GH_ENCRYPTED_ED25519_IV }}
      run: TRAVIS_OS_NAME=osx travis/upload.sh
    - name: Upload macOS plugin descriptors
      uses: actions/upload-artifact@v4
      with:
        name: plug-descr-mac
        path: temp/output/universal/*.descr
  build_windows:
    name: CI for Windows
    runs-on: windows-latest
    steps:
    - name: Checkout for Windows
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        path-type: inherit
        install: >-
          mingw-w64-x86_64-toolchain mingw-w64-x86_64-libzip mingw-w64-x86_64-pkg-config mingw-w64-x86_64-dlfcn
          git make tar unzip xz zip mingw-w64-x86_64-clang mingw-w64-x86_64-libblocksruntime
          mingw-w64-x86_64-jansson mingw-w64-x86_64-gtk3 mingw-w64-x86_64-gtk2 mingw-w64-x86_64-mpg123
          mingw-w64-x86_64-flac mingw-w64-x86_64-curl mingw-w64-x86_64-portaudio mingw-w64-x86_64-faad2 mingw-w64-x86_64-flac
          mingw-w64-x86_64-wavpack mingw-w64-x86_64-libvorbis mingw-w64-x86_64-libogg mingw-w64-x86_64-opusfile mingw-w64-x86_64-opus
          mingw-w64-x86_64-libsndfile mingw-w64-x86_64-libsamplerate mingw-w64-x86_64-yasm rsync patch autoconf automake autotools dos2unix
    - name: Build for Windows
      shell: msys2 {0}
      run: TRAVIS_OS_NAME=windows travis/build.sh
    - name: Upload for Windows
      env:
          gh_ed25519_key: ${{ secrets.GH_ENCRYPTED_ED25519_KEY }}
          gh_ed25519_iv: ${{ secrets.GH_ENCRYPTED_ED25519_IV }}
      shell: msys2 {0}
      run: TRAVIS_OS_NAME=windows travis/upload.sh
    - name: Upload windows plugin descriptors
      uses: actions/upload-artifact@v4
      with:
        name: plug-descr-win
        path: temp/output/x86_64/*.descr
  build_html:
    name: HTML update build
    needs: [build_linux, build_windows, build_macos]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout for Linux
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Download plugin descriptors
      uses: actions/download-artifact@v4
      with:
        pattern: plug-descr-*
        path: temp/output/x86_64
        merge-multiple: true
    - name: Build and Upload HTML
      uses: docker://ubuntu:16.04
      with:
        args: |
          /bin/bash -c "
            apt-get -qq update &&
            apt-get install -y -qq perl wget zip bzip2 openssh-client rsync git gcc g++ &&
            TRAVIS_OS_NAME=linux gh_ed25519_key= gh_ed25519_iv= travis/build_html.sh &&
            TRAVIS_OS_NAME=linux travis/upload_html.sh
          "
      env:
          gh_ed25519_key: ${{ secrets.GH_ENCRYPTED_ED25519_KEY }}
          gh_ed25519_iv: ${{ secrets.GH_ENCRYPTED_ED25519_IV }}
