name: Build for Linux

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    name: CI for Linux
    runs-on: ubuntu-latest
    container: ubuntu:14.04
    steps:
    - name: Install dependencies for Linux
      run: |
        apt-get -qq update
        apt-get install -y -qq autopoint automake autoconf intltool libc6-dev yasm libglib2.0-bin perl wget zip bzip2 make libtool pkg-config fakeroot clang openssh-client rsync git gcc g++ fontconfig xorg libharfbuzz0b libthai0 libwrap0 libsndfile1 libasyncns0
        sed -i 's/mozilla\/DST_Root_CA_X3\.crt/\!mozilla\/DST_Root_CA_X3\.crt/' /etc/ca-certificates.conf
        update-ca-certificates
    - name: Checkout for Linux
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build for Linux
      run: TRAVIS_OS_NAME=linux travis/build.sh
    - name: Upload for Linux
      env:
          gh_rsa_key: ${{ secrets.GH_ENCRYPTED_RSA_KEY }}
          gh_rsa_iv: ${{ secrets.GH_ENCRYPTED_RSA_IV }}
      run: TRAVIS_OS_NAME=linux travis/upload.sh
